modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"

[[mods]] #mandatory
modId="radiocraft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="RadioCraft" #mandatory
logoFile="logo.png" #optional
credits="Funded by the ARRL." #optional
description='''

'''

[[dependencies.radiocraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.radiocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
